- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download todo from Nexus
  get_url:
    url: http://172.31.3.191:8081/repository/todo/todo-1.0.1.zip
    dest: /root/todo
    username: admin
    password: shivark@99

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/todo
    dest: /root
    remote_src: yes

- name: Copy todos Service 
  copy:
    src: /root/ansible/roles/todo/files/todo.service
    dest: /etc/systemd/system/todo.service
    remote_src: yes

- name: Start todo Service 
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes

